language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
  - '10'

before_install:
  - npm install -g npm

script:
  - npm test

after_script:
  - npm run coveralls
  
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
